# Example: https://docs.github.com/cn/actions/quickstart
# Document: https://docs.github.com/cn/enterprise-server@3.1/actions/using-workflows/workflow-syntax-for-github-actions

name: The CI Flow
on:
  push:
    branches:
      - main
      - testing
jobs:
  The-CI-Flow:
    runs-on: ubuntu-latest
    steps:
      - run: echo $(pwd)
      - run: echo $(ls)
      - run: bash /home/runner/work/golib/golib/.github/workflowsdeploy/start.sh
      - run: bash ./deploy/code_check.sh
      - run: bash ./deploy/unit_test.sh
      - run: bash ./deploy/stop.sh
